name: film_hub
description: "Filmhub - A Flutter app for browsing movies and TV shows."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.1
  reactive_button: ^0.0.9
  dartz: ^0.10.1
  dio: ^6.1.1
  logger: ^1.1.0
  get_it: ^7.2.0
  shared_preferences: ^2.1.1
  flutter_svg: ^2.0.7
  fan_carousel_image_slider: ^1.0.0
  youtube_player_flutter: ^9.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.5.0
  build_runner: ^2.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
